import express from 'express';
import bcrypt from 'bcryptjs';
import jwt from 'jsonwebtoken';
import { authenticateToken, AuthRequest } from '../middleware/auth';
import { userRepository } from '../repositories/userRepository';
import { JWT_SECRET } from '../config';

const router = express.Router();

// Remove runtime seedAdmin() - relying on DB seed script

router.post('/register', async (req, res) => {
    const { name, email, password } = req.body;

    if (!name || !email || !password) {
        return res.status(400).json({ message: 'Name, email, and password are required' });
    }

    const emailRegex = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;
    if (!emailRegex.test(email)) {
        return res.status(400).json({ message: 'Invalid email format' });
    }

    if (password.length < 8) {
        return res.status(400).json({ message: 'Password must be at least 8 characters long' });
    }

    try {
        const existingUser = await userRepository.findByEmail(email);
        if (existingUser) {
            return res.status(409).json({ message: 'Email already in use' });
        }

        const salt = await bcrypt.genSalt(10);
        const passwordHash = await bcrypt.hash(password, salt);

        // id will be generated by repository (timestamp/uuid)
        const newUser = await userRepository.create({
            name,
            email,
            passwordHash,
            role: 'user'
        });

        const token = jwt.sign(
            { id: newUser.id, name: newUser.name, email: newUser.email, role: newUser.role },
            JWT_SECRET,
            { expiresIn: '24h' }
        );

        res.status(201).json({
            token,
            user: {
                id: newUser.id,
                name: newUser.name,
                email: newUser.email,
                role: newUser.role
            }
        });
    } catch (error) {
        console.error('Register error:', error);
        res.status(500).json({ message: 'Server error during registration' });
    }
});

router.post('/login', async (req, res) => {
    console.log('🔑 LOGIN ATTEMPT:', { email: req.body.email });

    try {
        const { email, password } = req.body;

        // 1. Validate input
        if (!email || !password) {
            console.log('❌ Missing email or password');
            return res.status(400).json({ message: 'Email and password required' });
        }

        // 2. Find user
        console.log('🔍 Searching user in database...');
        const user = await userRepository.findByEmail(email);

        if (!user) {
            console.log('❌ User not found:', email);
            return res.status(401).json({ message: 'Invalid credentials' });
        }

        console.log('✅ User found:', user.email);

        if (!user.passwordHash) {
            console.log('❌ User has no password hash (possibly oauth?)');
            return res.status(401).json({ message: 'Invalid credentials' });
        }

        // 3. Compare password
        const isMatch = await bcrypt.compare(password, user.passwordHash);

        if (!isMatch) {
            console.log('❌ Password mismatch for:', email);
            return res.status(401).json({ message: 'Invalid credentials' });
        }

        console.log('✅ Login successful for:', email);

        // 4. Generate JWT token
        const token = jwt.sign(
            { id: user.id, name: user.name, email: user.email, role: user.role },
            JWT_SECRET,
            { expiresIn: '7d' }
        );

        res.json({
            message: 'Login successful',
            token,
            user: {
                id: user.id,
                email: user.email,
                name: user.name,
                role: user.role
            }
        });

    } catch (error: any) {
        console.error('🔥 LOGIN ERROR DETAILS:');
        console.error('Error message:', error.message);
        console.error('Error stack:', error.stack);
        console.error('Request body:', req.body);

        res.status(500).json({
            message: 'Login failed',
            error: error.message
        });
    }
});

router.get('/me', authenticateToken, (req: AuthRequest, res) => {
    // Return user info from token (middleware)
    // Optionally fetch fresh from DB:
    // const user = await userRepository.findById(req.user.id);
    res.json({ user: req.user });
});

export default router;
